### ISSUE TITLE
converger hardcodes metron port to 3457

### ISSUE THREAD

**Issue by roxtar** [cloudfoundry-incubator/converger#1]
The converger [hardcodes the metron port to be 3457](https://github.com/cloudfoundry-incubator/converger/blob/master/cmd/converger/main.go#L81)

The metron port can be configured in CloudFoundry to be something other than 3457, so a change to the metron port will break metrics.

**Comment by ematpl** [comment]
Hi, @roxtar,

The Diego team will address this across the release in https://www.pivotaltracker.com/story/show/103689460, so I'l close this issue out in favor of that.

Thanks,
Eric
